"""TBDG Install Schedule — authenticated delivery of the scheduling tool.

The tool is a self-contained HTML page generated by the scheduling pipeline
(scheduler/build_review.py). It contains client names, home addresses,
phone numbers and install dates baked directly into its embedded data, so
it must NOT be a file in the git repo (private or not — see
scheduler/RULES.md) or the frontend's public/ tree, either of which would
expose it to anyone with repo or URL access. It lives in Postgres instead,
pushed there directly by scheduler/publish_pages.py (never committed, never
baked into the deploy image), and this router serves it only to a
signed-in user — main.py attaches the Supabase-JWT auth dependency to
every /api router.

Pages are kept per season, keyed on (season, name) — publishing a new
autumn's tool adds a row rather than overwriting last year's, so an old
season's routed plan stays openable (migrations/013). /seasons lists what
has actually been published, newest first, and /page defaults to the newest
PUBLISHED season rather than to season_for(): between 1 February and the
day the new season's tool is first built there is no current-season page,
and the tool must still open last season instead of 404ing.

It also stores the reschedule state (which stop sits on which crew-day,
plus approvals). That state is deliberately SHARED, not per-user: several
staff work through client reschedule requests over the same season, and a
per-user document would let two people silently diverge with no merge. It
is keyed on the schedule build version instead, so state saved against an
older build is never applied to a regenerated schedule by accident. The
season is recorded alongside it purely so a season can be FOUND without
knowing its build hash — `version` stays the primary key, and stays the
guard that stops a 2026 placement document being replayed onto a 2027
build (row numbers are re-assigned by each season's sheet).

Storage follows the `preferences` router's convention: an app-owned table
in the `ll_app` schema, a jsonb document, and a `FOR UPDATE` read-
modify-write so concurrent saves serialise rather than both landing on the
same stale snapshot.
"""
import json
import os
from datetime import datetime
from typing import Any

from fastapi import APIRouter, Body, Depends, HTTPException, Request
from fastapi.responses import HTMLResponse, JSONResponse

from app.apis.user_context import get_request_user_id
from app.auth.supabase_auth import get_current_user
from app.libs import client_season, roles
from app.libs.db import ensure_schema_once, get_conn
from app.libs.jsonutil import loads_json as _loads
from app.libs.season import season_for

router = APIRouter(prefix="/install-schedule")

#: The warehouse display login (role `viewer`) may read the tool and its
#: state, never save -- see app.libs.roles.
VIEWER_READ = True

ALLOWED = {"index.html", "map.html"}

#: One shared document per schedule build. Not a user id — see the module
#: docstring.
MAX_DOC_BYTES = 2_000_000


def _clean_season(season: str) -> str:
    """A season is the four-digit year its October falls in (see app.libs.season).

    Validated rather than trusted so it can be interpolated into a query
    parameter without a surprise: anything that is not four digits is a
    client bug, not a season nobody has published yet.
    """
    s = (season or "").strip()
    if len(s) != 4 or not s.isdigit():
        raise HTTPException(status_code=400, detail="Bad season")
    return s


async def _latest_published_season(conn, file: str) -> str | None:
    """The newest season with a published `file`, or None if there are none.

    Deliberately NOT season_for(): the current season has no page until the
    pipeline first publishes it, and for most of the year (Feb through the
    autumn build) that means the newest published page is last season's. The
    tool should open that, not an error. Seasons are four-digit years, so a
    text sort is a chronological sort.
    """
    return await conn.fetchval(
        "SELECT season FROM ll_app.install_schedule_pages "
        " WHERE name = $1 ORDER BY season DESC LIMIT 1",
        file,
    )


@router.get("/page", response_class=HTMLResponse)
async def get_install_schedule_page(
    file: str = "index.html", season: str | None = None
) -> str:
    if file not in ALLOWED:
        raise HTTPException(status_code=404, detail="Unknown page")
    # Local template preview (scheduler/preview_template.py): serve a file
    # built from this checkout's template instead of the published page.
    # Only honoured when the variable is set AND the file exists, so a
    # deployment that has neither behaves exactly as before.
    preview = os.getenv("INSTALL_SCHEDULE_PREVIEW_PAGE")
    if preview and file == "index.html" and os.path.isfile(preview):
        with open(preview, encoding="utf-8") as f:
            return f.read()
    want = _clean_season(season) if season is not None else None
    try:
        conn = await get_conn()
    except Exception as exc:
        raise HTTPException(
            status_code=503, detail="Schedule storage unavailable"
        ) from exc
    try:
        await ensure_schema(conn)
        if want is None:
            want = await _latest_published_season(conn, file)
        row = (
            await conn.fetchrow(
                "SELECT html FROM ll_app.install_schedule_pages "
                " WHERE season = $1 AND name = $2",
                want,
                file,
            )
            if want
            else None
        )
    finally:
        await conn.close()
    if not row:
        raise HTTPException(
            status_code=404,
            detail=(
                f"No {want} schedule published — run scheduler/publish_pages.py"
                if want
                else "Schedule not published yet — run scheduler/publish_pages.py"
            ),
        )
    return row["html"]


@router.get("/seasons")
async def list_seasons() -> dict:
    """Seasons with a published page, newest first — the season picker's list.

    Reports the current season separately as well as flagging it in the list,
    because the two can disagree: right after rollover the current season has
    nothing published yet, and the picker needs to be able to say so rather
    than silently present last season as if it were this one.

    Never 404s and degrades to an empty list on a storage outage, like
    /state and /history: an empty picker is a better failure than a page
    that will not render.
    """
    current = str(season_for())
    try:
        conn = await get_conn()
    except Exception:
        return {"seasons": [], "currentSeason": current, "storage": "unavailable"}
    try:
        await ensure_schema(conn)
        rows = await conn.fetch(
            "SELECT season, max(updated_at) AS updated_at, count(*) AS pages "
            "  FROM ll_app.install_schedule_pages "
            " GROUP BY season ORDER BY season DESC"
        )
    finally:
        await conn.close()
    return {
        "currentSeason": current,
        "seasons": [
            {
                "season": r["season"],
                "publishedAt": (
                    r["updated_at"].isoformat() if r["updated_at"] else None
                ),
                "pages": r["pages"],
                "current": r["season"] == current,
            }
            for r in rows
        ],
    }


# ─── Shared reschedule state ─────────────────────────────────────────────────

#: Keep at most this many history rows per schedule version -- an append-
#: only log with no cap would grow forever across a season of frequent
#: small saves (the tool debounces to one save per 600ms of inactivity,
#: but that's still potentially hundreds of saves over several weeks).
MAX_HISTORY_PER_VERSION = 200

#: Bootstrap for a database that has never seen these tables -- a fresh dev
#: or test instance. It describes the POST-013 shape, so a fresh database and
#: a migrated one end up identical.
#:
#: It deliberately does not reproduce 013's surgery (the backfill, the NOT
#: NULL, the primary-key swap). CREATE TABLE IF NOT EXISTS is a no-op on a
#: database that already has the table, so on the live database this whole
#: block does nothing and cannot fight the migration; the ADD COLUMN IF NOT
#: EXISTS lines are likewise no-ops there. Turning an old un-migrated table
#: into a season-keyed one is 013's job and 013's alone -- it has to move the
#: existing rows to a season before it can key on one, and that is not
#: something a request handler should be doing on the way past.
DDL = """
CREATE SCHEMA IF NOT EXISTS ll_app;

-- The compiled tool itself (client names, addresses, phone numbers baked
-- into its embedded data) -- deliberately NOT a file in the git repo or
-- the deploy image (see the module docstring). scheduler/publish_pages.py
-- pushes a fresh build here directly, one row per (season, page), so
-- publishing a new autumn adds to the archive instead of erasing it.
CREATE TABLE IF NOT EXISTS ll_app.install_schedule_pages (
    season     text NOT NULL,
    name       text NOT NULL,
    html       text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT install_schedule_pages_pkey PRIMARY KEY (season, name)
);

CREATE TABLE IF NOT EXISTS ll_app.install_schedule_state (
    version    text PRIMARY KEY,
    season     text,
    state      jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_by text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
-- version stays the primary key: it is what guarantees one season's
-- placement document is never replayed onto another season's build. season
-- is only here so a season can be found without knowing its build hash.
ALTER TABLE ll_app.install_schedule_state ADD COLUMN IF NOT EXISTS season text;
CREATE INDEX IF NOT EXISTS install_schedule_state_season_idx
    ON ll_app.install_schedule_state (season);

-- Append-only save history, so several staff working the same schedule can
-- see who changed what and roll back a mistake -- the same shape as a
-- Google Doc's version history. Restoring an old version does not delete
-- anything from this table; it just writes a new current state (and a new
-- history row) that happens to match the old one, so the trail stays intact.
CREATE TABLE IF NOT EXISTS ll_app.install_schedule_history (
    id         bigserial PRIMARY KEY,
    version    text NOT NULL,
    season     text,
    state      jsonb NOT NULL,
    updated_by text,
    created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE ll_app.install_schedule_history ADD COLUMN IF NOT EXISTS season text;
CREATE INDEX IF NOT EXISTS install_schedule_history_version_idx
    ON ll_app.install_schedule_history (version, created_at DESC);
"""


async def ensure_schema(conn):
    async def _ddl():
        await conn.execute(DDL)

    await ensure_schema_once("install_schedule", _ddl)


def _clean_version(version: str) -> str:
    v = (version or "").strip()
    if not v or len(v) > 64 or not v.replace("-", "").replace("_", "").isalnum():
        raise HTTPException(status_code=400, detail="Bad schedule version")
    return v


#: What survives a rebuild. The state document mixes two different things: the
#: SCHEDULE (placement, moves, approvals, comments -- all keyed on row numbers
#: and crew-day ids that a rebuild reassigns) and the PEOPLE (who is on the
#: roster, when they can work, who is on which crew-day). Only the schedule is
#: really tied to a build; the roster is a fact about the business.
#:
#: They lived in one document, so they shared its fate: the version is a hash of
#: the schedule's contents, and fixing a placement bug changed the schedule,
#: changed the hash, and left an 18-person roster stranded under a key nothing
#: would look up again. The tool fell back to roster_seed.json -- which stores
#: everyone with `dates: []`, meaning available never -- so the season's crew
#: silently became unschedulable.
CARRY_FORWARD_KEYS = ("roster", "staffing")


async def _inheritable_people(conn, version: str, season: str | None) -> dict | None:
    """Roster and staffing from the most recent earlier build, if any.

    Only ever consulted when THIS build has no state of its own, so it can
    never overwrite something a person saved. Staffing is included because it
    is self-cleaning downstream -- normStaffing() drops assignments pointing at
    crew-day ids the current build does not have -- so a rebuild keeps the
    assignments that still make sense and quietly forgets the rest.
    """
    row = await conn.fetchrow(
        """
        SELECT version, state, updated_at
          FROM ll_app.install_schedule_state
         WHERE version <> $1
           AND ($2::text IS NULL OR season IS NULL OR season = $2)
           AND jsonb_array_length(COALESCE(state->'roster', '[]'::jsonb)) > 0
         ORDER BY updated_at DESC
         LIMIT 1
        """,
        version, season,
    )
    if not row:
        return None
    prior = _loads(row["state"]) or {}
    carried = {k: prior[k] for k in CARRY_FORWARD_KEYS if prior.get(k)}
    if not carried:
        return None
    carried["inheritedFrom"] = row["version"]
    return carried


# ─── Contractor info (admin only) ────────────────────────────────────────────
#
# Each roster person can carry what's needed to set them up as a 1099
# contractor: legal name, home address, whether they're tracked for a 1099
# and whether direct deposit is on file (user, 2026-10-07). This router is
# readable by staff, the warehouse display (viewer) and production, so those
# fields are stripped from every roster this router returns to anyone below
# admin -- the page hiding the section is a convenience, this is the guard.
#
# Saves are the other half. PUT /state replaces the whole document, and a
# non-admin's page never had the fields, so its save would wipe them -- and a
# non-admin could otherwise set them by hand. So a non-admin save takes each
# person's contractor fields from the stored state (matched by person id)
# and ignores whatever was sent. Someone a non-admin adds has none; someone
# they delete is gone, as before. Admin saves keep the fields as sent.
#
# Mirrored by contractorFields() in scheduler/review_template.html. The other
# roster readers (lead pages, /me, Settings > Users, install costs, the
# calendar feed) all go through app.libs.schedule_board._norm_person, which
# keeps only id/name/title/email/phone, so none of them can carry these.
SENSITIVE_ROSTER_FIELDS = (
    "legalName", "street", "city", "state", "zip", "tax1099", "directDeposit",
)

def sees_contractor_info(role: Any) -> bool:
    """admin and super_admin. Anything else -- including a role we failed to
    resolve, or a handler called without one -- does not."""
    return isinstance(role, str) and roles.at_least(role, "admin")


async def caller_role(request: Request) -> str:
    """The signed-in caller's role. The router-level require_role check has
    usually resolved it already for this request; otherwise resolve it here
    (the lookup is cached). Local dev with auth off is super_admin, matching
    require_role."""
    if os.getenv("AUTH_DISABLED", "").lower() == "true" and os.getenv("ENV", "dev") == "dev":
        return "super_admin"
    cached = getattr(getattr(request, "state", None), "ll_role", None)
    if isinstance(cached, str):
        return cached
    return await roles.resolve_role(get_current_user(request).email)


def _strip_person(p: Any) -> Any:
    if not isinstance(p, dict):
        return p
    return {k: v for k, v in p.items() if k not in SENSITIVE_ROSTER_FIELDS}


def strip_roster(doc: Any) -> Any:
    """A copy of a state (or inherit) document with every roster person's
    contractor fields removed. Anything that isn't a dict passes through."""
    if not isinstance(doc, dict) or not isinstance(doc.get("roster"), list):
        return doc
    return {**doc, "roster": [_strip_person(p) for p in doc["roster"]]}


def keep_stored_contractor_info(state: dict, stored: Any) -> dict:
    """A non-admin's save: every person's contractor fields come from the
    stored state (by id), never from the request."""
    roster = state.get("roster")
    if not isinstance(roster, list):
        return state
    prior: dict[str, dict] = {}
    if isinstance(stored, dict) and isinstance(stored.get("roster"), list):
        for p in stored["roster"]:
            if isinstance(p, dict) and p.get("id") not in (None, ""):
                prior[str(p["id"])] = {
                    k: p[k] for k in SENSITIVE_ROSTER_FIELDS if k in p
                }
    out = []
    for p in roster:
        if isinstance(p, dict):
            p = {**_strip_person(p), **prior.get(str(p.get("id") or ""), {})}
        out.append(p)
    return {**state, "roster": out}


@router.get("/state")
async def get_state(
    version: str, season: str | None = None, role: str = Depends(caller_role)
) -> dict:
    """Current shared state for a schedule build.

    Never 404s on a missing row: no state yet is the normal case on a fresh
    build, and the tool must fall back to its own baseline rather than show
    an error. A storage outage degrades the same way — the tool keeps
    working from localStorage.

    When there is no state for this build, the response carries the roster and
    staffing from the most recent earlier one under `inherit`, so a rebuild
    does not silently empty the crew. It is offered, not applied: the tool
    treats it as a starting point exactly as it treats the seed file, and the
    first real save writes it into this build's own row.
    """
    v = _clean_version(version)
    try:
        conn = await get_conn()
    except Exception:
        return {"version": v, "state": None, "storage": "unavailable"}
    try:
        await ensure_schema(conn)
        row = await conn.fetchrow(
            "SELECT state, updated_by, updated_at "
            "FROM ll_app.install_schedule_state WHERE version = $1",
            v,
        )
        inherit = None if row else await _inheritable_people(conn, v, season)
    finally:
        await conn.close()
    full = sees_contractor_info(role)
    if not row:
        return {"version": v, "state": None,
                "inherit": inherit if full else strip_roster(inherit)}
    state = _loads(row["state"])
    return {
        "version": v,
        "state": state if full else strip_roster(state),
        "updatedBy": row["updated_by"],
        "updatedAt": row["updated_at"].isoformat() if row["updated_at"] else None,
    }


# Leaf & Ledger is the source of truth for whether a client is installing, so a
# removal (or a hold) made in the scheduler has to reach the client record --
# not stay in this tool's own state where the Clients tab never sees it. Before
# this, a client pulled from the season still had a 2026 client_activity row
# reading "Scheduled 2026-11-25", which is what the Clients tab showed and what
# the scheduler's own popup contradicted.
#
# The summary wording, the flag names and the rule for what survives a re-sync
# all live in app.libs.client_season, shared with scheduler/sync_clients.py
# and the Clients tab's own season editor -- one summarize(), not three.
NOT_INSTALLING_SUMMARY = client_season.NOT_INSTALLING_SUMMARY
NO_DATE_SUMMARY = client_season.NO_DATE_SUMMARY


async def _reconcile_flags(
    conn,
    season: str,
    not_installing: list[str],
    hold: list[str] | None = None,
    dates: dict[str, str] | None = None,
) -> dict:
    """Make client_activity agree with the scheduler about who is installing
    and who is on hold.

    Idempotent and narrow: it only ever touches this season's christmas_install
    rows, and only the ones whose flags disagree with the lists. Both
    directions are handled, so putting a client back restores the line rather
    than leaving a permanent "not installing" behind. Edits go through
    client_season.apply_edits so they are stamped exactly like an edit made on
    the Clients tab, and the summary is rebuilt from the row, not composed here.
    """
    def _fold(names):
        return {n.strip().lower() for n in (names or []) if isinstance(n, str) and n.strip()}

    want_out = _fold(not_installing)
    # hold=None means the page did not say (an older build): leave holds as
    # they are rather than reading "nothing sent" as "nobody is on hold".
    want_hold = (_fold(hold) - want_out) if hold is not None else None
    # Keyed the same way the names are matched -- case/whitespace-folded --
    # so a marking that also knows the date the client was pulled off of can
    # say so, instead of just "not installing" with nothing to compare against
    # what staff remember booking (user, 2026-09-04).
    dates_by_name = {
        n.strip().lower(): d for n, d in (dates or {}).items()
        if isinstance(n, str) and n.strip() and isinstance(d, str) and d.strip()
    }
    rows = await conn.fetch(
        "SELECT ca.id, ca.summary, ca.detail, cl.name, "
        "       COALESCE((ca.detail->>'not_installing')::boolean, false) AS flagged, "
        "       COALESCE((ca.detail->>'hold')::boolean, false) AS held "
        "  FROM client_activity ca JOIN clients cl ON cl.id = ca.client_id "
        " WHERE ca.season = $1 AND ca.kind = 'christmas_install'",
        season,
    )
    marked = cleared = 0
    for r in rows:
        key = (r["name"] or "").strip().lower()
        is_out = key in want_out
        is_hold = (key in want_hold) if want_hold is not None else bool(r.get("held"))
        if is_out == bool(r["flagged"]) and is_hold == bool(r.get("held")):
            continue  # already agrees -- most rows, most saves
        detail = _loads(r["detail"]) or {}
        if not isinstance(detail, dict):
            detail = {}
        edits: dict = {}
        if is_out != bool(r["flagged"]):
            edits["not_installing"] = is_out
            if is_out and dates_by_name.get(key):
                detail["was_scheduled"] = dates_by_name[key]
        if is_hold != bool(r.get("held")):
            edits["hold"] = is_hold
        detail = client_season.apply_edits(detail, edits)
        if is_out or is_hold:
            marked += 1
        else:
            cleared += 1
        await conn.execute(
            "UPDATE client_activity SET summary = $2, detail = $3::jsonb, updated_at = now() "
            " WHERE id = $1",
            r["id"], client_season.summarize(detail), json.dumps(detail, default=str),
        )
    return {"marked": marked, "cleared": cleared}


# The board owns install dates (user, 2026-10-06: "whatever date is on the
# install schedule calendar is the one we go with"). Hold and not-installing
# already reached the client card on every save; a stop moved to another date
# did not, so the Clients tab kept the old date (Comments #14-17). The page
# now sends `dateMoves`: only the clients whose board date changed since its
# last successful save (a drag, the move dialog, a whole-day move, the slot
# finder, an undo, a history restore -- anything that changes the board goes
# through the same save). This writes those dates onto this season's card.
#
# Deliberately one-way and narrow: it never reads a card date back onto the
# board, it only touches clients the page says moved, and it never creates a
# season row that is not there. Clients whose card already disagreed before
# this shipped are left for a person to review (scripts/report_board_vs_card
# _dates.py lists them) rather than bulk-rewritten by whoever saves first.
#
# The card stores no crew or time for the current season (`crew` on a season
# row is LAST year's crew as typed on the sheet, and crew numbers on the board
# are positional per date, so they would go stale on the next move), so only
# the date is written.
DATE_MOVE_KINDS = {"install": "install_date", "takedown": "takedown_date"}
#: How many board moves a card remembers in detail.date_history.
DATE_HISTORY_KEEP = 20


def _fold_name(s: Any) -> str:
    """normName() in the page: case, commas, periods and spacing don't count."""
    out = str(s or "").strip().lower().replace(",", "").replace(".", "")
    return " ".join(out.split())


def _clean_date_moves(raw: Any, season: str) -> list[dict]:
    """The page's dateMoves, validated: a known kind, a real ISO date inside
    this season (1 Oct - 31 Jan), and a name or a client id to match on."""
    from app.libs.season import season_span

    if not isinstance(raw, list):
        return []
    try:
        lo, hi = season_span(int(season))
    except (TypeError, ValueError):
        return []
    out = []
    for m in raw[:2000]:
        if not isinstance(m, dict) or m.get("kind") not in DATE_MOVE_KINDS:
            continue
        try:
            date = client_season.coerce_field("install_date", m.get("date"))
        except client_season.FieldError:
            continue
        if not date or not (lo.isoformat() <= date <= hi.isoformat()):
            continue
        cid = m.get("id")
        cid = cid if isinstance(cid, int) and not isinstance(cid, bool) else None
        name = _fold_name(m.get("name"))
        if not name and cid is None:
            continue
        frm = m.get("from") if isinstance(m.get("from"), str) else None
        out.append({"id": cid, "name": name, "kind": m["kind"], "date": date, "from": frm})
    return out


async def _sync_board_dates(conn, season: str, moves: list[dict], by: str | None = None) -> dict:
    """Write each moved client's board date onto this season's card.

    Matches on the client id when the page knows it, else on any spelling the
    app has for the client (name, the sheet's spelling, former names), folded
    the way the page folds them. A card that already shows the date is left
    alone, so a re-sent move (a retried save) writes nothing. The edit goes
    through client_season.apply_edits, so it is stamped as an app edit and the
    spreadsheet sync never puts the old date back; the previous date is kept
    in detail.date_history.
    """
    if not moves:
        return {"updated": 0, "unmatched": 0}
    rows = await conn.fetch(
        "SELECT ca.id, ca.client_id, ca.detail, cl.name, cl.sheet_name, cl.former_names "
        "  FROM client_activity ca JOIN clients cl ON cl.id = ca.client_id "
        " WHERE ca.season = $1 AND ca.kind = 'christmas_install'",
        season,
    )
    by_id: dict[int, Any] = {}
    by_name: dict[str, list] = {}
    for r in rows:
        by_id[r["client_id"]] = r
        spellings = {r["name"], r.get("sheet_name"), *(r.get("former_names") or [])}
        for s in spellings:
            k = _fold_name(s)
            if k:
                by_name.setdefault(k, []).append(r)
    updated = unmatched = 0
    details: dict[int, dict] = {}
    for m in moves:
        r = by_id.get(m["id"]) if m["id"] is not None else None
        if r is None:
            hits = {x["id"]: x for x in by_name.get(m["name"], [])}
            # Two different clients answering to one spelling: guessing would
            # put a date on the wrong card, so leave both alone.
            r = next(iter(hits.values())) if len(hits) == 1 else None
        if r is None:
            unmatched += 1
            continue
        detail = details.get(r["id"])
        if detail is None:
            detail = _loads(r["detail"]) or {}
            if not isinstance(detail, dict):
                detail = {}
        key = DATE_MOVE_KINDS[m["kind"]]
        if detail.get("not_installing") or detail.get(key) == m["date"]:
            continue
        old = detail.get(key)
        detail = client_season.apply_edits(detail, {key: m["date"]})
        hist = detail.get("date_history")
        hist = hist if isinstance(hist, list) else []
        hist.append({"field": key, "from": old, "to": m["date"],
                     "at": client_season.now_iso(), "by": by, "source": "install schedule"})
        detail["date_history"] = hist[-DATE_HISTORY_KEEP:]
        details[r["id"]] = detail
    for row_id, detail in details.items():
        await conn.execute(
            "UPDATE client_activity SET summary = $2, detail = $3::jsonb, "
            "       occurred_at = COALESCE($4::date, occurred_at), updated_at = now() "
            " WHERE id = $1",
            row_id, client_season.summarize(detail), json.dumps(detail, default=str),
            _iso_to_date(detail.get("install_date")),
        )
        updated += 1
    return {"updated": updated, "unmatched": unmatched}


def _iso_to_date(s: Any):
    import datetime as _dt

    try:
        return _dt.date.fromisoformat(str(s)[:10]) if s else None
    except ValueError:
        return None


# ─── Stale-tab guard ─────────────────────────────────────────────────────────
#
# PUT /state replaces the whole document, so a tab that loaded an OLD state and
# saves it later erases everything written in between. On 10/8/2026 a 1099
# import (8:29 PM CT) added 23 roster people and their contractor details; a
# tab opened before it saved at 9:03 PM while sending mass texts and silently
# erased all of it. With board dates now written onto client cards, a stale
# tab could also put old dates on cards.
#
# So every save says which version of the document it was built on
# (`baseUpdatedAt`: the updatedAt the page last loaded or saved). If anyone has
# written since -- another tab, or a server-side script, all of which bump
# updated_at -- the save is refused with 409 and the CURRENT state, nothing is
# written (no state, no history row, no card dates), and the page merges its
# own unsaved changes onto that state and retries (mergeShared() in
# scheduler/review_template.html).
#
# The comparison is equality, not "newer than": updated_at is only ever
# compared with a value this server handed out, so any write at all in
# between counts, whatever the clocks did. Writes here move updated_at
# strictly forward (GREATEST(clock_timestamp(), updated_at + 1 microsecond))
# so two saves can never share a stamp.
#
# Pages published before this shipped send no `baseUpdatedAt`. Refusing them
# would stop every open tab saving until the page is republished, so they are
# accepted (and logged) with two protections for exactly what the 10/8 save
# destroyed: an old page's save can't remove roster people, and can't erase a
# person's contractor fields by leaving them out. Set
# INSTALL_SCHEDULE_REQUIRE_BASE=true once the new page is published to refuse
# them instead (428: reload the page).
REQUIRE_BASE_ENV = "INSTALL_SCHEDULE_REQUIRE_BASE"


def _parse_ts(raw: Any) -> datetime:
    """An updatedAt this API handed out (datetime.isoformat())."""
    if not isinstance(raw, str) or not raw.strip():
        raise ValueError("not a timestamp")
    ts = datetime.fromisoformat(raw.strip().replace("Z", "+00:00"))
    if ts.tzinfo is None:
        raise ValueError("timestamp without a timezone")
    return ts


def _has_content(doc: Any) -> bool:
    return isinstance(doc, dict) and bool(doc)


def is_stale(base_at: datetime | None, stored_doc: Any, stored_at: datetime | None) -> bool:
    """Would this save overwrite something its page never saw?

    Nothing stored yet (no row, or the empty row PUT itself just inserted)
    can't be overwritten. A page that saw no state (base None) is stale as soon
    as someone has saved. Otherwise any write since the page's base counts."""
    if not _has_content(stored_doc):
        return False
    if base_at is None or stored_at is None:
        return True
    return stored_at != base_at


def keep_for_legacy_save(state: dict, stored: Any) -> tuple[dict, dict]:
    """A save from a page that sends no base timestamp (published before the
    guard). It can't be checked for staleness, so it is not allowed to do the
    two things the 10/8 stale save did: drop roster people (anyone stored but
    missing from the save is kept, at the end), or erase a person's
    contractor fields by leaving all of them out (they are kept from the
    stored person). Returns (state, what was kept) for the log."""
    kept = {"people": [], "contractor": []}
    roster = state.get("roster")
    if not isinstance(roster, list) or not isinstance(stored, dict) \
            or not isinstance(stored.get("roster"), list):
        return state, kept
    stored_people = {
        str(p["id"]): p for p in stored["roster"]
        if isinstance(p, dict) and p.get("id") not in (None, "")
    }
    sent_ids = set()
    out = []
    for p in roster:
        if isinstance(p, dict):
            pid = str(p.get("id") or "")
            sent_ids.add(pid)
            prior = stored_people.get(pid)
            if prior and not any(k in p for k in SENSITIVE_ROSTER_FIELDS):
                extra = {k: prior[k] for k in SENSITIVE_ROSTER_FIELDS if k in prior}
                if extra:
                    p = {**p, **extra}
                    kept["contractor"].append(pid)
        out.append(p)
    for pid, p in stored_people.items():
        if pid not in sent_ids:
            out.append(p)
            kept["people"].append(pid)
    return {**state, "roster": out}, kept


@router.put("/state")
async def put_state(
    request: Request, body: Any = Body(default=None), role: str = Depends(caller_role)
) -> dict:
    """Replace the shared state for one schedule build.

    Whole-document write rather than a deep merge on the server: the page
    knows which entities it changed, the server doesn't. The row lock
    serialises concurrent saves, and the stale-tab guard (above) refuses a
    save built on an older document with 409 + the current state, which the
    page merges its own changes onto and retries. A success returns the new
    updatedAt, the page's base for its next save.
    """
    if not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="Body must be an object")
    v = _clean_version(str(body.get("version") or ""))
    state = body.get("state")
    if not isinstance(state, dict):
        raise HTTPException(status_code=400, detail="state must be an object")
    # Checked on what was sent; the stored contractor fields merged back in
    # below are a few hundred bytes at most.
    if len(json.dumps(state)) > MAX_DOC_BYTES:
        raise HTTPException(status_code=413, detail="State document too large")
    full = sees_contractor_info(role)

    # The stale-tab guard's input. Absent = a page published before the guard.
    has_base = "baseUpdatedAt" in body
    base_at = None
    if has_base and body.get("baseUpdatedAt") is not None:
        try:
            base_at = _parse_ts(body.get("baseUpdatedAt"))
        except ValueError:
            raise HTTPException(status_code=400, detail="Bad baseUpdatedAt") from None
    if not has_base and os.getenv(REQUIRE_BASE_ENV, "").lower() == "true":
        raise HTTPException(
            status_code=428,
            detail="This Install Schedule page is out of date. Reload it to keep saving.",
        )

    # Stamp the row with the season the tool says it is, so a season's saves
    # can be found without knowing its build hash. Read tolerantly and never
    # fatally: a page cached from before the tool sent a season still has to
    # be able to save. `version` remains the primary key and remains the
    # guard against cross-season replay -- season is a label, not a key.
    raw_season = str(state.get("season") or "").strip()
    payload_season = raw_season if (len(raw_season) == 4 and raw_season.isdigit()) else None

    user_id = get_request_user_id(request)
    try:
        conn = await get_conn()
    except Exception as exc:
        raise HTTPException(
            status_code=503, detail="Schedule state storage unavailable"
        ) from exc
    try:
        await ensure_schema(conn)
        async with conn.transaction():
            await conn.execute(
                "INSERT INTO ll_app.install_schedule_state "
                "(version, season, state, updated_by) "
                "VALUES ($1, $2, '{}'::jsonb, $3) ON CONFLICT (version) DO NOTHING",
                v,
                payload_season,
                user_id,
            )
            cur = await conn.fetchrow(
                "SELECT state, updated_by, updated_at FROM ll_app.install_schedule_state "
                "WHERE version = $1 FOR UPDATE",
                v,
            )
            stored = _loads(cur["state"]) if cur else None
            stored_at = cur["updated_at"] if cur else None
            # Under the row lock, so nothing can be written between this check
            # and the write below.
            if has_base and is_stale(base_at, stored, stored_at):
                print(
                    f"install-schedule: refused a stale save of {v} by {user_id} "
                    f"(page base {base_at.isoformat() if base_at else None}, "
                    f"stored {stored_at.isoformat() if stored_at else None} "
                    f"by {cur['updated_by'] if cur else None})"
                )
                conflict = {
                    "conflict": True,
                    "detail": "Someone saved this schedule after this page loaded it.",
                    "version": v,
                    "state": stored if full else strip_roster(stored),
                    "updatedBy": cur["updated_by"] if cur else None,
                    "updatedAt": stored_at.isoformat() if stored_at else None,
                }
            else:
                conflict = None
                if not has_base:
                    state, kept = keep_for_legacy_save(state, stored)
                    print(
                        f"install-schedule: save of {v} by {user_id} from a page without "
                        f"baseUpdatedAt (stored {stored_at.isoformat() if stored_at else None}); "
                        f"kept {len(kept['people'])} people it left out "
                        f"{kept['people'][:30]} and contractor info for {len(kept['contractor'])}"
                    )
                if not full:
                    state = keep_stored_contractor_info(state, stored)
            if conflict is not None:
                # Nothing written: no state, no history row, no card dates.
                return JSONResponse(status_code=409, content=conflict)
            encoded = json.dumps(state)
            new_at = await conn.fetchval(
                # COALESCE, not a plain assignment: an older cached page sends
                # no season, and letting that blank out the label a newer save
                # already wrote would lose it for good. updated_at only ever
                # moves forward (see the stale-tab guard).
                "UPDATE ll_app.install_schedule_state "
                "SET state = $2::jsonb, updated_by = $3, "
                "    season = COALESCE($4, season), "
                "    updated_at = GREATEST(clock_timestamp(), updated_at + interval '1 microsecond') "
                "WHERE version = $1 RETURNING updated_at",
                v,
                encoded,
                user_id,
                payload_season,
            )
            # Append to history, then trim to the retention cap -- every
            # save gets a row, restoring an old one included, so the trail
            # itself is never rewritten.
            await conn.execute(
                "INSERT INTO ll_app.install_schedule_history "
                "(version, season, state, updated_by) "
                "VALUES ($1, $2, $3::jsonb, $4)",
                v,
                payload_season,
                encoded,
                user_id,
            )
            await conn.execute(
                "DELETE FROM ll_app.install_schedule_history "
                "WHERE version = $1 AND id NOT IN ("
                "  SELECT id FROM ll_app.install_schedule_history "
                "  WHERE version = $1 ORDER BY created_at DESC LIMIT $2"
                ")",
                v,
                MAX_HISTORY_PER_VERSION,
            )
            # Write the not-installing / on-hold decisions through to the
            # client record, inside the same transaction as the state save so
            # the two cannot disagree if one half fails.
            #
            # Keyed on the field being PRESENT, not on it being non-empty: a
            # page cached from before this shipped sends no such key, and
            # treating that as "nobody is excluded" would clear every flag the
            # newer clients had set. Absent means "this client has nothing to
            # say", which is different from "the list is empty". `holdNames`
            # is newer still, so it is read the same way and an older page
            # that does not send it leaves holds exactly as they are.
            if "notInstallingNames" in state:
                names = state.get("notInstallingNames") or []
                raw_dates = state.get("notInstallingDates")
                dates = raw_dates if isinstance(raw_dates, dict) else {}
                holds = state.get("holdNames") if "holdNames" in state else None
                if payload_season and isinstance(names, list):
                    try:
                        await _reconcile_flags(
                            conn, payload_season, names,
                            holds if isinstance(holds, list) else None, dates,
                        )
                    except Exception as exc:  # noqa: BLE001
                        # The schedule save is the user's actual action and must
                        # not fail because the write-through did; the next save
                        # reconciles again from scratch.
                        print(f"not-installing write-through skipped: {exc}")
            # Board dates onto the cards (see _sync_board_dates). Only for
            # the live season: an archived season is a record, and its page
            # never saves anyway -- this is the server-side half of that.
            # Viewer / production / lead logins never reach this handler
            # (the router's role check refuses their PUT).
            if "dateMoves" in state and payload_season and payload_season == str(season_for()):
                moves = _clean_date_moves(state.get("dateMoves"), payload_season)
                if moves:
                    try:
                        # A savepoint: a failed card write must not abort the
                        # schedule save around it.
                        async with conn.transaction():
                            await _sync_board_dates(conn, payload_season, moves, user_id)
                    except Exception as exc:  # noqa: BLE001
                        print(f"board-date write-through skipped: {exc}")
    finally:
        await conn.close()
    return {
        "version": v,
        "ok": True,
        "updatedBy": user_id,
        "updatedAt": new_at.isoformat() if isinstance(new_at, datetime) else None,
    }


@router.get("/history")
async def list_history(version: str, limit: int = 50) -> dict:
    """Lightweight save history for a schedule build -- timestamp and who,
    not the full state (kept small; fetch one entry's state on demand to
    preview or restore it). Newest first, like a Google Doc's version list.
    """
    v = _clean_version(version)
    limit = max(1, min(limit, MAX_HISTORY_PER_VERSION))
    try:
        conn = await get_conn()
    except Exception:
        return {"version": v, "entries": [], "storage": "unavailable"}
    try:
        await ensure_schema(conn)
        rows = await conn.fetch(
            "SELECT id, updated_by, created_at FROM ll_app.install_schedule_history "
            "WHERE version = $1 ORDER BY created_at DESC LIMIT $2",
            v,
            limit,
        )
    finally:
        await conn.close()
    return {
        "version": v,
        "entries": [
            {
                "id": r["id"],
                "updatedBy": r["updated_by"],
                "createdAt": r["created_at"].isoformat() if r["created_at"] else None,
            }
            for r in rows
        ],
    }


@router.get("/history/{entry_id}")
async def get_history_entry(
    entry_id: int, version: str, role: str = Depends(caller_role)
) -> dict:
    """One historical save's full state, for previewing or restoring it.
    Scoped to `version` too so an id from a different (e.g. regenerated)
    schedule build can't be replayed onto this one."""
    v = _clean_version(version)
    try:
        conn = await get_conn()
    except Exception as exc:
        raise HTTPException(
            status_code=503, detail="Schedule state storage unavailable"
        ) from exc
    try:
        await ensure_schema(conn)
        row = await conn.fetchrow(
            "SELECT id, state, updated_by, created_at "
            "FROM ll_app.install_schedule_history WHERE id = $1 AND version = $2",
            entry_id,
            v,
        )
    finally:
        await conn.close()
    if not row:
        raise HTTPException(status_code=404, detail="History entry not found")
    state = _loads(row["state"])
    return {
        "id": row["id"],
        "version": v,
        "state": state if sees_contractor_info(role) else strip_roster(state),
        "updatedBy": row["updated_by"],
        "createdAt": row["created_at"].isoformat() if row["created_at"] else None,
    }


@router.get("/calendar-link", dependencies=[Depends(roles.require_role("staff"))])
async def calendar_link() -> dict:
    """The office's calendar subscription link (app/apis/install_calendar),
    for the tool page's "Add to Google Calendar" button.

    Staff and up only: this router is otherwise readable by the warehouse
    display (VIEWER_READ) and production, and the link carries the feed's
    secret -- whoever holds it sees every client's address and phone. The
    path is in roles.PRODUCTION_DENY for the same reason. 404 while
    INSTALL_CALENDAR_TOKEN is unset, so the button stays hidden.
    """
    token = os.getenv("INSTALL_CALENDAR_TOKEN", "")
    if not token:
        raise HTTPException(status_code=404, detail="Calendar feed is not set up")
    return {"path": f"/api/install-calendar/feed.ics?token={token}"}
