"""TBDG Install Schedule — authenticated delivery of the scheduling tool.

The tool is a self-contained HTML page generated by the scheduling pipeline
(scheduler/build_review.py syncs it into backend/protected/). It contains
client names, home addresses and phone numbers, so it must NOT live in the
frontend's public/ tree where static hosting would serve it to anyone with
the URL. This router returns it only to a signed-in user — main.py attaches
the Supabase-JWT auth dependency to every /api router.

It also stores the reschedule state (which stop sits on which crew-day,
plus approvals). That state is deliberately SHARED, not per-user: several
staff work through client reschedule requests over the same season, and a
per-user document would let two people silently diverge with no merge. It
is keyed on the schedule build version instead, so state saved against an
older build is never applied to a regenerated schedule by accident.

Storage follows the `preferences` router's convention: an app-owned table
in the `ll_app` schema, a jsonb document, and a `FOR UPDATE` read-
modify-write so concurrent saves serialise rather than both landing on the
same stale snapshot. It cannot live on the filesystem — `backend/protected`
is baked into the image at build time, so a redeploy would silently revert
every accommodation staff had recorded.
"""
import json
import os
import pathlib
from typing import Any

import asyncpg
from fastapi import APIRouter, Body, HTTPException, Request
from fastapi.responses import HTMLResponse

from app.apis.user_context import get_request_user_id

router = APIRouter(prefix="/install-schedule")

BASE = pathlib.Path(__file__).resolve().parents[3] / "protected" / "install-schedule"
ALLOWED = {"index.html", "map.html"}

#: One shared document per schedule build. Not a user id — see the module
#: docstring.
MAX_DOC_BYTES = 2_000_000


@router.get("/page", response_class=HTMLResponse)
def get_install_schedule_page(file: str = "index.html") -> str:
    if file not in ALLOWED:
        raise HTTPException(status_code=404, detail="Unknown page")
    path = BASE / file
    if not path.is_file():
        raise HTTPException(
            status_code=404,
            detail="Schedule not generated yet — run the scheduling pipeline",
        )
    return path.read_text(encoding="utf-8")


# ─── Shared reschedule state ─────────────────────────────────────────────────


async def get_conn():
    return await asyncpg.connect(
        os.environ.get("DATABASE_URL"), statement_cache_size=0
    )


_SCHEMA_READY = False

DDL = """
CREATE SCHEMA IF NOT EXISTS ll_app;

CREATE TABLE IF NOT EXISTS ll_app.install_schedule_state (
    version    text PRIMARY KEY,
    state      jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_by text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
"""


async def ensure_schema(conn):
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    await conn.execute(DDL)
    _SCHEMA_READY = True


def _loads(raw: Any) -> Any:
    """json.loads that returns None rather than raising. asyncpg may hand back
    a decoded object or the raw jsonb text depending on codecs."""
    if raw is None or isinstance(raw, (dict, list)):
        return raw
    if not isinstance(raw, str):
        return None
    try:
        return json.loads(raw)
    except ValueError:
        return None


def _clean_version(version: str) -> str:
    v = (version or "").strip()
    if not v or len(v) > 64 or not v.replace("-", "").replace("_", "").isalnum():
        raise HTTPException(status_code=400, detail="Bad schedule version")
    return v


@router.get("/state")
async def get_state(version: str) -> dict:
    """Current shared state for a schedule build.

    Never 404s on a missing row: no state yet is the normal case on a fresh
    build, and the tool must fall back to its own baseline rather than show
    an error. A storage outage degrades the same way — the tool keeps
    working from localStorage.
    """
    v = _clean_version(version)
    try:
        conn = await get_conn()
    except Exception:
        return {"version": v, "state": None, "storage": "unavailable"}
    try:
        await ensure_schema(conn)
        row = await conn.fetchrow(
            "SELECT state, updated_by, updated_at "
            "FROM ll_app.install_schedule_state WHERE version = $1",
            v,
        )
    finally:
        await conn.close()
    if not row:
        return {"version": v, "state": None}
    return {
        "version": v,
        "state": _loads(row["state"]),
        "updatedBy": row["updated_by"],
        "updatedAt": row["updated_at"].isoformat() if row["updated_at"] else None,
    }


@router.put("/state")
async def put_state(request: Request, body: Any = Body(default=None)) -> dict:
    """Replace the shared state for one schedule build.

    Whole-document write rather than a deep merge: the payload is a single
    placement snapshot ({row -> day}), and merging two snapshots key by key
    would produce a schedule neither person actually approved. The row lock
    serialises concurrent saves, and the response reports who last wrote so
    the tool can tell the user their view was superseded.
    """
    if not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="Body must be an object")
    v = _clean_version(str(body.get("version") or ""))
    state = body.get("state")
    if not isinstance(state, dict):
        raise HTTPException(status_code=400, detail="state must be an object")
    encoded = json.dumps(state)
    if len(encoded) > MAX_DOC_BYTES:
        raise HTTPException(status_code=413, detail="State document too large")

    user_id = get_request_user_id(request)
    try:
        conn = await get_conn()
    except Exception as exc:
        raise HTTPException(
            status_code=503, detail="Schedule state storage unavailable"
        ) from exc
    try:
        await ensure_schema(conn)
        async with conn.transaction():
            await conn.execute(
                "INSERT INTO ll_app.install_schedule_state (version, state, updated_by) "
                "VALUES ($1, '{}'::jsonb, $2) ON CONFLICT (version) DO NOTHING",
                v,
                user_id,
            )
            await conn.fetchval(
                "SELECT state FROM ll_app.install_schedule_state "
                "WHERE version = $1 FOR UPDATE",
                v,
            )
            await conn.execute(
                "UPDATE ll_app.install_schedule_state "
                "SET state = $2::jsonb, updated_by = $3, updated_at = now() "
                "WHERE version = $1",
                v,
                encoded,
                user_id,
            )
    finally:
        await conn.close()
    return {"version": v, "ok": True, "updatedBy": user_id}
