import React, { useEffect, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Loader2, TreePine } from "components/icons";
import Layout from "components/Layout";
import { auth } from "app/auth/auth";
import { apiFetch } from "utils/apiFetch";
import { currentMe } from "utils/me";
import { type InstallView, legacyView, pathForView, viewForPath, withHostFlags } from "utils/installViews";

/**
 * TBDG Install Schedule — the Christmas install scheduling tool.
 *
 * The tool is a self-contained static page generated by the scheduling
 * pipeline (scheduler/build_review.py). It holds client names, addresses and
 * phone numbers, so it is served through the AUTHENTICATED
 * /api/install-schedule/page endpoint rather than from public/ — we fetch it
 * with the signed-in user's token and inject it into a srcDoc iframe.
 * (srcDoc keeps the parent origin, so the tool's localStorage persistence —
 * approvals and drag-drop moves — keeps working.)
 *
 * The tool also saves reschedule decisions to a SHARED server document so
 * two staff working client requests don't silently diverge. srcDoc content
 * has no Supabase session of its own, so we postMessage the token in;
 * without it the tool degrades to localStorage only, which is exactly how
 * the standalone file behaves.
 *
 * Sending on the iframe's `onLoad` alone was a one-shot guess at timing: if
 * that fires (or the token fetch resolves) even slightly out of step with
 * the tool's own message listener registering, the token is dropped with no
 * retry, and every server-backed feature (contact edits, comments, shared
 * reschedule state) silently falls back to read-only/local-only for the
 * rest of that page load. The tool now posts `tbdg-ready` the moment its
 * listener exists; sending in direct response to that is what actually
 * guarantees delivery. `onLoad` stays wired too, as a second attempt.
 */
type ToolWindow = Window & { tbdgFlush?: () => void; tbdgViews?: boolean };

/** Builds published before the app nav existed have no `tbdg-view` listener:
 *  press their own tab button instead, so the nav still works until the new
 *  template is published. */
const LEGACY_TAB_BUTTON: Record<InstallView, string> = {
  days: "viewdays",
  cal: "viewcal",
  staff: "viewstaff",
  roster: "viewroster",
};

export default function InstallSchedule() {
  const location = useLocation();
  const navigate = useNavigate();
  const routeView = viewForPath(location.pathname);
  const [html, setHtml] = useState<string | null>(null);
  // The tool's TV mode (a wall display): it tells us when it's on, and we
  // cover the whole window -- sidebar included -- with the tool.
  const [tv, setTv] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const frameRef = useRef<HTMLIFrameElement | null>(null);
  // The view the page is showing, as far as we know: what it was opened on,
  // then whatever it last reported or we last asked for. Route changes that
  // already match it send nothing, so the page and the URL never ping-pong.
  const pageView = useRef<InstallView>(routeView);
  const pathRef = useRef(location.pathname);
  pathRef.current = location.pathname;
  const heardFromPage = useRef(false);
  const pageReady = useRef(false);

  // Old links: /install-schedule?view=calendar, ?tab=roster or #staffing.
  useEffect(() => {
    const v = legacyView(location.search, location.hash);
    if (v && v !== "days") navigate(pathForView(v), { replace: true });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await apiFetch("/api/install-schedule/page");
        if (!res.ok) {
          const detail = await res.json().catch(() => null);
          throw new Error(detail?.detail || `Failed to load (${res.status})`);
        }
        const text = await res.text();
        const me = currentMe();
        const viewOnly = Boolean(me?.viewOnly || me?.readOnly);
        // Opens on the view of the route we're on by the time it arrived.
        const view = viewForPath(pathRef.current);
        pageView.current = view;
        if (!cancelled) setHtml(withHostFlags(text, view, viewOnly, Boolean(me?.viewOnly)));
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const sendToken = async () => {
    try {
      const token = await auth.getAuthHeaderValue();
      if (!token) return;
      frameRef.current?.contentWindow?.postMessage(
        { type: "tbdg-auth", token },
        window.location.origin,
      );
    } catch {
      /* tool falls back to localStorage */
    }
  };

  /** Show `view` in the already-loaded page: no reload, no remount. */
  const showView = (view: InstallView) => {
    const w = frameRef.current?.contentWindow as ToolWindow | null | undefined;
    if (!w) return;
    pageView.current = view;
    try {
      if (!w.tbdgViews) {
        (w.document.getElementById(LEGACY_TAB_BUTTON[view]) as HTMLButtonElement | null)?.click();
        return;
      }
    } catch {
      /* not reachable: fall through to the message */
    }
    w.postMessage({ type: "tbdg-view", view }, window.location.origin);
  };

  // A nav click between the four schedule routes lands here, with the same
  // iframe still mounted (user-routes.tsx: one parent route for all four).
  useEffect(() => {
    if (!html || !pageReady.current) return;
    if (routeView !== pageView.current) showView(routeView);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [routeView, html]);

  // Leaving the schedule unmounts the iframe, which kills the tool's 200ms
  // debounced save with it. Ask the tool (same origin, so its window is
  // reachable) to flush synchronously first; older published builds without
  // the hook simply have nothing to call. Switching between the four
  // schedule routes does NOT unmount it, so nothing is flushed or lost there.
  // Re-run when `html` lands so the frame captured here is the one that
  // actually mounted (it does not exist before then).
  useEffect(() => {
    const frame = frameRef.current;
    return () => {
      try {
        const w = frame?.contentWindow as ToolWindow | null | undefined;
        w?.tbdgFlush?.();
      } catch {
        /* cross-origin or already gone */
      }
    };
  }, [html]);

  useEffect(() => {
    const onMessage = (e: MessageEvent) => {
      if (e.origin !== window.location.origin) return;
      if (e.source !== frameRef.current?.contentWindow) return;
      const type = e.data?.type;
      if (type === "tbdg-ready") {
        sendToken();
        // Navigated while it was still loading: catch it up.
        pageReady.current = true;
        const want = viewForPath(pathRef.current);
        if (want !== pageView.current) showView(want);
      }
      if (type === "tbdg-tv") setTv(Boolean(e.data.on));
      // The page changed view on its own (a day opened from the Calendar,
      // TV mode ending, the warehouse display opening on the wall calendar):
      // follow it in the URL so the nav highlights the right entry.
      if (type === "tbdg-view" && typeof e.data.view === "string") {
        const view = e.data.view as InstallView;
        pageView.current = view;
        const path = pathForView(view);
        if (path !== pathRef.current) navigate(path, { replace: !heardFromPage.current });
        heardFromPage.current = true;
      }
    };
    window.addEventListener("message", onMessage);
    return () => window.removeEventListener("message", onMessage);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <Layout>
      <div className={tv ? "fixed inset-0 z-[60] flex flex-col bg-[#f7f6f2]" : "flex h-full min-h-0 flex-col"}>
        {error ? (
          <div className="flex flex-1 flex-col items-center justify-center gap-3 text-stone-500">
            <TreePine className="h-8 w-8 text-stone-400" />
            <p className="text-sm font-medium">{error}</p>
          </div>
        ) : html === null ? (
          <div className="flex flex-1 items-center justify-center text-stone-400">
            <Loader2 className="h-6 w-6 animate-spin" />
          </div>
        ) : (
          <iframe
            ref={frameRef}
            srcDoc={html}
            title="TBDG Install Schedule"
            className="h-full w-full flex-1 border-0"
            allow="fullscreen"
            allowFullScreen
            onLoad={() => {
              pageReady.current = true;
              sendToken();
            }}
          />
        )}
      </div>
    </Layout>
  );
}
