import React, { useEffect, useState } from "react";
import { Loader2, TreePine } from "lucide-react";
import Layout from "components/Layout";
import { apiFetch } from "utils/apiFetch";

/**
 * TBDG Install Schedule — the Christmas install scheduling tool.
 *
 * The tool is a self-contained static page generated by the scheduling
 * pipeline (tbdg-christmas-schedule/build_review.py). It holds client names,
 * addresses and phone numbers, so it is served through the AUTHENTICATED
 * /api/install-schedule/page endpoint rather than from public/ — we fetch it
 * with the signed-in user's token and inject it into a srcDoc iframe.
 * (srcDoc keeps the parent origin, so the tool's localStorage persistence —
 * approvals and drag-drop moves — keeps working.)
 */
export default function InstallSchedule() {
  const [html, setHtml] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await apiFetch("/api/install-schedule/page");
        if (!res.ok) {
          const detail = await res.json().catch(() => null);
          throw new Error(detail?.detail || `Failed to load (${res.status})`);
        }
        const text = await res.text();
        if (!cancelled) setHtml(text);
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <Layout>
      <div className="flex h-[calc(100vh-0px)] min-h-0 flex-col">
        {error ? (
          <div className="flex flex-1 flex-col items-center justify-center gap-3 text-stone-500">
            <TreePine className="h-8 w-8 text-stone-400" />
            <p className="text-sm font-medium">{error}</p>
          </div>
        ) : html === null ? (
          <div className="flex flex-1 items-center justify-center text-stone-400">
            <Loader2 className="h-6 w-6 animate-spin" />
          </div>
        ) : (
          <iframe
            srcDoc={html}
            title="TBDG Install Schedule"
            className="h-full w-full flex-1 border-0"
          />
        )}
      </div>
    </Layout>
  );
}
