
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";



import AdminDashboard from "./pages/AdminDashboard.tsx";
import App from "./pages/App.tsx";
import Arrangements from "./pages/Arrangements.tsx";
import Clients from "./pages/Clients.tsx";
import Designs from "./pages/Designs.tsx";
import Favorites from "./pages/Favorites.tsx";
import Invoice from "./pages/Invoice.tsx";
import Library from "./pages/Library.tsx";
import Mockups from "./pages/Mockups.tsx";
import Orders from "./pages/Orders.tsx";
import OrnamentCalculator from "./pages/OrnamentCalculator.tsx";
import CatalogSearch from "./pages/CatalogSearch.tsx";
import Settings from "./pages/Settings.tsx";
import Suppliers from "./pages/Suppliers.tsx";

export const userRoutes: RouteObject[] = [

	{ path: "/admin-dashboard", element: <AdminDashboard /> },
	{ path: "/admindashboard", element: <AdminDashboard /> },
	{ path: "/", element: <App /> },
	{ path: "/arrangements", element: <Arrangements /> },
	{ path: "/clients", element: <Clients /> },
	{ path: "/clients/project", element: <Arrangements /> },
	{ path: "/designs", element: <Designs /> },
	// The builder renders standalone here (it detects this pathname). Routing to
	// it directly — rather than nesting it inside Designs — keeps a single Layout.
	{ path: "/designs/new", element: <Arrangements /> },
	{ path: "/projects", element: <Arrangements /> },
	{ path: "/favorites", element: <Favorites /> },
	{ path: "/invoice", element: <Invoice /> },
	{ path: "/library", element: <Library /> },
	{ path: "/mockups", element: <Mockups /> },
	{ path: "/orders", element: <Orders /> },
	{ path: "/ornament-calculator", element: <OrnamentCalculator /> },
	{ path: "/ornamentcalculator", element: <OrnamentCalculator /> },
	{ path: "/search", element: <CatalogSearch /> },
	{ path: "/settings", element: <Settings /> },
	{ path: "/suppliers", element: <Suppliers /> },

];
