
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";

import { lazyWithReload } from "./utils/lazyWithReload";

// Each page is its own chunk, loaded on first navigation to its route. The
// Suspense boundary that covers these lives in router.tsx, wrapping the
// <Outlet /> shared by every route below (so it also covers the sidebar/guard
// layer without remounting it per navigation). lazyWithReload wraps
// React.lazy so a stale chunk reference after a deploy (an open tab whose
// index.html points at chunk hashes that no longer exist) recovers with a
// single automatic reload instead of a permanent error.
const AdminDashboard = lazyWithReload(() => import("./pages/AdminDashboard.tsx"));
const App = lazyWithReload(() => import("./pages/App.tsx"));
const Arrangements = lazyWithReload(() => import("./pages/Arrangements.tsx"));
const Clients = lazyWithReload(() => import("./pages/Clients.tsx"));
const Designs = lazyWithReload(() => import("./pages/Designs.tsx"));
const Favorites = lazyWithReload(() => import("./pages/Favorites.tsx"));
const Comments = lazyWithReload(() => import("./pages/Comments.tsx"));
const Invoice = lazyWithReload(() => import("./pages/Invoice.tsx"));
const Jobs = lazyWithReload(() => import("./pages/Jobs.tsx"));
const RequestForm = lazyWithReload(() => import("./pages/RequestForm.tsx"));
const Sourcing = lazyWithReload(() => import("./pages/Sourcing.tsx"));
const Mockups = lazyWithReload(() => import("./pages/Mockups.tsx"));
const Orders = lazyWithReload(() => import("./pages/Orders.tsx"));
const OrnamentCalculator = lazyWithReload(() => import("./pages/OrnamentCalculator.tsx"));
const TreeCounts = lazyWithReload(() => import("./pages/TreeCounts.tsx"));
const CatalogSearch = lazyWithReload(() => import("./pages/CatalogSearch.tsx"));
const InstallSchedule = lazyWithReload(() => import("./pages/InstallSchedule.tsx"));
const Shifts = lazyWithReload(() => import("./pages/Shifts.tsx"));
const Settings = lazyWithReload(() => import("./pages/Settings.tsx"));
const Suppliers = lazyWithReload(() => import("./pages/Suppliers.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/admin-dashboard", element: <AdminDashboard /> },
	{ path: "/", element: <App /> },
	{ path: "/arrangements", element: <Arrangements /> },
	{ path: "/clients", element: <Clients /> },
	{ path: "/clients/project", element: <Arrangements /> },
	{ path: "/designs", element: <Designs /> },
	// Both design routes render <Designs>; it keeps the header + All Designs /
	// New Design toggle mounted and swaps only the body, so you can toggle back.
	{ path: "/designs/new", element: <Designs /> },
	{ path: "/projects", element: <Arrangements /> },
	{ path: "/favorites", element: <Favorites /> },
	{ path: "/comments", element: <Comments /> },
	{ path: "/invoice", element: <Invoice /> },
	{ path: "/jobs", element: <Jobs /> },
	{ path: "/jobs/:jobId", element: <Jobs /> },
	{ path: "/requests", element: <RequestForm /> },
	{ path: "/requests/:requestId", element: <RequestForm /> },
	// The purchaser's full worksheet. Not in the sidebar; reachable by link.
	{ path: "/sourcing", element: <Sourcing /> },
	{ path: "/sourcing/:jobId", element: <Sourcing /> },
	{ path: "/mockups", element: <Mockups /> },
	{ path: "/orders", element: <Orders /> },
	{ path: "/install-schedule", element: <InstallSchedule /> },
	{ path: "/ornament-calculator", element: <OrnamentCalculator /> },
	{ path: "/tree-counts", element: <TreeCounts /> },
	{ path: "/search", element: <CatalogSearch /> },
	{ path: "/settings", element: <Settings /> },
	// Leads land here and can open nothing else (app/auth/RoleGate.tsx).
	{ path: "/shifts", element: <Shifts /> },
	{ path: "/suppliers", element: <Suppliers /> },

];
